### ISSUE TITLE
ID3Parser get in trouble by parsing too big files

### ISSUE THREAD

**Issue by schenklklopfer** [ChristophWurst/ID3Parser#1]
As mentioned in https://github.com/nextcloud/server/issues/14922 there is a problem with parsing too big files.

These files are RAW records produced by IceCast2 and stored in a NextCloud instance.  
Everytime ID3Parser tries to parse those files, it kills the PHP7.2-FPM running the NextCloud. (Load from hell, everything stucks, needs to restart FPM)

To get rid of this I need to deactivate ID3Parser after every Update of NextCloud with:
`INSERT -> public function isAvailable(\OCP\Files\FileInfo $file) { return false; }`

**Comment by ChristophWurst** [comment]
Someone has to fix it, yes.

**Comment by ChristophWurst** [comment]
The current code of this library isn't really in a maintainable state unfortunately, so fixing this is a bit hard.

**Comment by schenklklopfer** [comment]
Since NC 17.0.1 the problem is gone.
